# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  roots.lupilabs.com:
    site_hosts:
      - canonical: roots.lupilabs.test
        redirects:
          - www.roots.lupilabs.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: wolf@lupilabs.com
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: manual
      cert: ~/IdeaProjects/roots-plugins/certs/lupilabs.test.crt
      key: ~/IdeaProjects/roots-plugins/certs/lupilabs.test.key
    cache:
      enabled: false
